spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cob
    username: postgres
    password: root
    
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
    
    
# Email Propeties
#===========================
email: 
 host: mail.smtp.host
 hostType: smtp.gmail.com
 factoryPort: mail.smtp.socketFactory.port
 factoryPortType: 465
 classes: mail.smtp.socketFactory.class
 classType: javax.net.ssl.SSLSocketFactory
 auth: mail.smtp.auth
 port: mail.smtp.port
 portType: 465
 from: jagadish.borra531@gmail.com
 password: Jagadish@2022    
    